{
 "title": "ModelServingMetrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Server Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Request Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(Requests2XX) / (sum(Requests4XX) +  sum(Requests2XX)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemoryUtilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "MemoryUtilization", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "DiskUtiliztion",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DiskUtilization", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(ts_inference_requests_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "DiskUsage", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Model Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PredictionTime(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "PredictionTime", "legendFormat": "{{job}}_{{ModelName}}" }
   ]
  },
  {
   "title": "Max PredictionTime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(PredictionTime)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(ts_inference_latency_microseconds[1m]) * 0.001",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TorchServe_Queue_Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(ts_queue_latency_microseconds[1m]) * 0.001",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Model Drift",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true
  },
  {
   "title": "Zscore - x1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(sum(train_input_mean_x1) - sum(input_mean_x1)) / sum(sqrt(train_input_mean_x1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zscore - x2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "(sum(train_input_mean_x2) - sum(input_mean_x2))/(sum(sqrt(train_input_var_x2)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Feature Variance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sqrt(input_var_x1)", "legendFormat": "input_var_x1" },
    { "expr": "sqrt(input_var_x2)", "legendFormat": "input_var_x1" }
   ]
  },
  {
   "title": "Inference Input Mean",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "input_mean_x1", "legendFormat": "input_mean_x1" },
    { "expr": "input_mean_x2", "legendFormat": "input_mean_x2" }
   ]
  },
  {
   "title": "Training Input Mean - x1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "train_input_mean_x1", "legendFormat": "train_input_mean_x1" },
    { "expr": "train_input_mean_x2", "legendFormat": "train_input_mean_x2" }
   ]
  }
 ]
}