{
 "title": "ModelServingMetrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Server Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "CPUUtilization", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "DiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "DiskUsage", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Model Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Input Feature Variance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "input_var_x1{instance=\"torchserve_green:8082\"}",
     "legendFormat": "x1_var"
    },
    {
     "expr": "input_var_x2{instance=\"torchserve_green:8082\"}",
     "legendFormat": "x2_var"
    }
   ]
  },
  {
   "title": "Input Feaures Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "input_mean_x1{job=\"torchserve_green\"}",
     "legendFormat": "x1"
    },
    {
     "expr": "input_mean_x2{job=\"torchserve_green\"}",
     "legendFormat": "x2"
    }
   ]
  },
  {
   "title": "Inference Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(ts_inference_latency_microseconds{hostname=\"76ecf155f3fc\"}[5m]) * 0.001",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TorchServe_Queue_Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(ts_queue_latency_microseconds[1m]) * 0.001",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}