global:
  scrape_interval: 15s # scrape interval 
  evaluation_interval: 15s # Evaluate rules 


rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'torchserve_green'
    static_configs:
      - targets: ['torchserve_green:8082']  # TorchServe Green Metrics

  - job_name: 'torchserve_blue'
    static_configs:
      - targets: ['torchserve_blue:8082']  # TorchServe Blue Metrics
      
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Node Exporter Metrics

  - job_name: 'train_data_distribution'
    static_configs:
      - targets: ['172.31.30.239:6001']  # Training Data Metrics
