{
 "title": "ModelServingMetrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Server Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total Request in Past 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(ts_inference_requests_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Request in Past 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(invalid_input_count[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(Requests2XX) / (sum(Requests4XX) +  sum(Requests2XX)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DiskUtiliztion",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DiskUtilization", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "MemoryUtilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "MemoryUtilization", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "rate(ts_inference_requests_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "targets": [
    { "expr": "DiskUsage", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Model Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PredictionTime(ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    { "expr": "PredictionTime", "legendFormat": "{{job}}_{{ModelName}}" }
   ]
  },
  {
   "title": "PredictionTime over Past 24h",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(PredictionTime[24h])",
     "legendFormat": "MAX_{{job}}"
    },
    {
     "expr": "avg_over_time(PredictionTime[24h])",
     "legendFormat": "AVG_{{job}}"
    }
   ]
  },
  {
   "title": "Inference Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "rate(ts_inference_latency_microseconds[1m]) * 0.001",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TorchServe_Queue_Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "rate(ts_queue_latency_microseconds[1m]) * 0.001",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Model Drift",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Zscore - x1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "(avg(train_input_mean_x1) - avg(input_mean_x1)) / avg(sqrt(train_input_var_x1))",
     "legendFormat": "(train_input_mean_x1 - input_mean_x1) / sqrt(train_input_var_x1)"
    }
   ]
  },
  {
   "title": "Zscore - x2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "(avg(train_input_mean_x2) - avg(input_mean_x2)) / avg(sqrt(train_input_var_x2))",
     "legendFormat": "(train_input_mean_x2 - input_mean_x2) / sqrt(train_input_var_x2)"
    }
   ]
  },
  {
   "title": "Inference Input Mean",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 20 },
   "targets": [
    { "expr": "input_mean_x1", "legendFormat": "input_mean_x1" },
    { "expr": "input_mean_x2", "legendFormat": "input_mean_x2" }
   ]
  },
  {
   "title": "Training Input Mean",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 20 },
   "targets": [
    { "expr": "train_input_mean_x1", "legendFormat": "train_input_mean_x1" },
    { "expr": "train_input_mean_x2", "legendFormat": "train_input_mean_x2" }
   ]
  },
  {
   "title": "Inference Input Var",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 20 },
   "targets": [
    { "expr": "input_var_x1", "legendFormat": "input_mean_x1" },
    { "expr": "input_var_x2", "legendFormat": "input_mean_x2" }
   ]
  },
  {
   "title": "Inference Input Var",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 20 },
   "targets": [
    { "expr": "train_input_var_x1", "legendFormat": "input_mean_x1" },
    { "expr": "train_input_var_x2", "legendFormat": "input_mean_x2" }
   ]
  }
 ]
}